# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/a2m_v2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: a2m
        password: a2m
    jpa:
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          use-new-id-generator-mappings: true
          show-sql: true
          properties:
            hibernate: 
              format_sql: true
                    
server:
    error:
      whitelabel:
        enabled: false
    port: 8443
    ssl:
      key-store: a2m.p12
      key-store-password: BI-1784-BJ
      keyStoreType: PKCS12
      keyAlias: tomcat
 
logging:
    file: /desarrollo/temp/logs/calendar
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        org.springframework.aop.framework.CglibAopProxy: ERROR
        org.springframework.test: INFO
        org.springframework.boot: INFO
        org.springframework.web: INFO
        es.a2m.calendar: DEBUG
        ROOT: INFO